### ISSUE TITLE
Add option to change svg render colors

### ISSUE THREAD

**Issue by Signynt** [akopdev/obsidian-textgrams#1]
It would be great to have an option to set the background and line render color of the diagrams. The option to set these colors to transparent would also be great, so you can set the background to be transparent. Optimally even a different setting for dark and light mode.

Currently the rendered diagrams look a bit out of place in dark themes, or any theme which doesn't use white as a background color.

**Comment by akopdev** [comment]
Hi @Signynt, 

The newly created release [0.6.0](https://github.com/akopdev/obsidian-textgrams/releases/tag/0.6.0) supports light and dark themes. Please, update your plugin and let me know what you think.

**Comment by Signynt** [comment]
Looks great, thanks, this solves the issue!
